// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe4bZAiFO_XYx-p-6KBYgyhWteR3sa08E',
    appId: '1:823285427125:web:e5dc86ab628daabd5a87fc',
    messagingSenderId: '823285427125',
    projectId: 'tap-game-test0709',
    authDomain: 'tap-game-test0709.firebaseapp.com',
    storageBucket: 'tap-game-test0709.firebasestorage.app',
    measurementId: 'G-6LF3D5214C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClP93nLE7hWaZRlRgTL3m6oZ0lzazNl3o',
    appId: '1:823285427125:android:8518d670b911e9af5a87fc',
    messagingSenderId: '823285427125',
    projectId: 'tap-game-test0709',
    storageBucket: 'tap-game-test0709.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8KQktVuYrsU-0r89Wz7Q9b0rfq5EOpTU',
    appId: '1:823285427125:ios:1ea3346148e980345a87fc',
    messagingSenderId: '823285427125',
    projectId: 'tap-game-test0709',
    storageBucket: 'tap-game-test0709.firebasestorage.app',
    iosBundleId: 'com.example.tapGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8KQktVuYrsU-0r89Wz7Q9b0rfq5EOpTU',
    appId: '1:823285427125:ios:1ea3346148e980345a87fc',
    messagingSenderId: '823285427125',
    projectId: 'tap-game-test0709',
    storageBucket: 'tap-game-test0709.firebasestorage.app',
    iosBundleId: 'com.example.tapGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe4bZAiFO_XYx-p-6KBYgyhWteR3sa08E',
    appId: '1:823285427125:web:6ef110c2935af69c5a87fc',
    messagingSenderId: '823285427125',
    projectId: 'tap-game-test0709',
    authDomain: 'tap-game-test0709.firebaseapp.com',
    storageBucket: 'tap-game-test0709.firebasestorage.app',
    measurementId: 'G-WFS40Y3M19',
  );
}
