// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4KF-1At7UebYZrvjjwgZsPEI7ovnENkA',
    appId: '1:726428747048:web:41f972b51edb85a41dfc1d',
    messagingSenderId: '726428747048',
    projectId: 'anatesting-969a6',
    authDomain: 'anatesting-969a6.firebaseapp.com',
    storageBucket: 'anatesting-969a6.firebasestorage.app',
    measurementId: 'G-K87KDPFKQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQCsOVyEYhYX4raQMLv_BqbKri065PdFA',
    appId: '1:726428747048:android:fa16895ff9789c5f1dfc1d',
    messagingSenderId: '726428747048',
    projectId: 'anatesting-969a6',
    storageBucket: 'anatesting-969a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC958OZlwPh7_cWMHWUWiLNfAcoArw8aF0',
    appId: '1:726428747048:ios:74e73392d33d366f1dfc1d',
    messagingSenderId: '726428747048',
    projectId: 'anatesting-969a6',
    storageBucket: 'anatesting-969a6.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppKensyu0702',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC958OZlwPh7_cWMHWUWiLNfAcoArw8aF0',
    appId: '1:726428747048:ios:74e73392d33d366f1dfc1d',
    messagingSenderId: '726428747048',
    projectId: 'anatesting-969a6',
    storageBucket: 'anatesting-969a6.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppKensyu0702',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4KF-1At7UebYZrvjjwgZsPEI7ovnENkA',
    appId: '1:726428747048:web:71d03086b9d64ec01dfc1d',
    messagingSenderId: '726428747048',
    projectId: 'anatesting-969a6',
    authDomain: 'anatesting-969a6.firebaseapp.com',
    storageBucket: 'anatesting-969a6.firebasestorage.app',
    measurementId: 'G-9HX9H077FV',
  );

}