// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzdq8qaK3psAj3hJ870WO9dRj3QL2Jkz4',
    appId: '1:81527832461:web:a519bf43515009d3d447c4',
    messagingSenderId: '81527832461',
    projectId: 'my-test-project-0702',
    authDomain: 'my-test-project-0702.firebaseapp.com',
    storageBucket: 'my-test-project-0702.firebasestorage.app',
    measurementId: 'G-FRPSWGLKVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNhfcLgucgGsyH3N9HaBRTHjqEyd-bfCY',
    appId: '1:81527832461:android:3e2e3171c8ac306bd447c4',
    messagingSenderId: '81527832461',
    projectId: 'my-test-project-0702',
    storageBucket: 'my-test-project-0702.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsVT40Vv2nmXXA7KM3HgkLo4LvYGcoc-c',
    appId: '1:81527832461:ios:14963550afa4778cd447c4',
    messagingSenderId: '81527832461',
    projectId: 'my-test-project-0702',
    storageBucket: 'my-test-project-0702.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationKensyu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsVT40Vv2nmXXA7KM3HgkLo4LvYGcoc-c',
    appId: '1:81527832461:ios:14963550afa4778cd447c4',
    messagingSenderId: '81527832461',
    projectId: 'my-test-project-0702',
    storageBucket: 'my-test-project-0702.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationKensyu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzdq8qaK3psAj3hJ870WO9dRj3QL2Jkz4',
    appId: '1:81527832461:web:5f939efb5e1871bad447c4',
    messagingSenderId: '81527832461',
    projectId: 'my-test-project-0702',
    authDomain: 'my-test-project-0702.firebaseapp.com',
    storageBucket: 'my-test-project-0702.firebasestorage.app',
    measurementId: 'G-C9VKLKE6X9',
  );
}
